WeLoveSpeed/welovespeed.com

_data/staff.yml

There's no "-" in "Clever Age"! ;-)

---

_talks/conferences/organizing-business-for-web-performance.md

correction typo

---

pages/fr/coc.md

MAJ du mail

---

pages/fr/infos-pratiques.md

correction typos

---

pages/en/sponsors.html

dans la page sponso anglaise, lien vers le dossier de sponsoring anglais

---

_includes/post.html

Remplacement de la mention de Sud Web par We Love Speed

---

_includes/schema.html

MAJ des infos schema.org

---

_config_prod.yml

Ajout de la variable tickets.price

---

pages/fr/contact.md

traduction du bouton en FR

---

_data/speakers.yml

MAJ titre ouest france

---

_config_prod.yml

Ouverture des ventes

---

_data/speakers.yml
_talks/conferences/css-rendering-performance.md

@jpvincent
https://5b4f4cff73f2cf6ece6e1c47--welovespeed.netlify.com/programme/#css-rendering-performance

tzi's talks

---

_data/speakers.yml

Bio de Nicolas en Lorem Ipsum
Bio en français et en anglais

Update Nicolas's bio

---

_talks/conferences/responsive-images-optimize-webperf.md

Finalisation de la description
Ajustements sur titre et description en anglais

Final version of talk title and description

---

_data/speakers.yml

Une tournure de phrase un peu bizarre

Amélioration de la lisibilité

---

_talks/conferences/responsive-images-optimize-webperf.md

Gros pavé indigeste
Découpage en paragraphes

Découpage en paragraphes, pour la lisibilité

---

pages/fr/infos-pratiques.md

Add missing "le"
A8 is far far away from Bordeaux
Wording and highways

Fix minor details on "infos-pratiques"

---

_includes/conferences.html
_talks/conferences/metrics-explained.md

On prévoit un lien vers les vidéos

---

_talks/conferences/chrome-ux-report.md
_talks/conferences/css-rendering-performance.md
_talks/conferences/fast-by-default-rebuilding-algolia-website.md
_talks/conferences/how-much-is-100ms-correlate-webperf-and-conversion.md
_talks/conferences/lightning-fast-ux.md
_talks/conferences/metrics-explained.md
_talks/conferences/organizing-business-for-web-performance.md
_talks/conferences/performance-budgets.md
_talks/conferences/responsive-images-optimize-webperf.md
_talks/conferences/ux-and-performance-metrics-that-matters.md
_talks/conferences/webperf-as-core-value.md

Les URL des vidéos ne sont pas contribuées.
Contribution des URLs des vidéos. 
**Ne pas merge tant que les vidéos ne sont pas publiques**.

:sparkles: Youtube video URLs

---

_includes/header-home.html

- Suppression du message d'attente pour la publication des vidéos sur la page d'accueil

Les vidéos sont dispos

---

_includes/header-home.html

Annonce qu'il y aura quelque chose en 2019, CTA vers newsletter et réseaux sociaux

Teasing 2019

---

_data/writeups.yml

Erreur de rattachement de Jonas Badalic à Clever Age
Nettoyage dans le fichier _data

Jonas Badalic is not from Clever Age

---

_data/translations.yml
_redirects
_tasks/postbuild.rake
pages/en/2019/informations.md

N/A
- Ajoute la traduction EN de la page “infos pratiques”

Add Informations (en) page

---

_data/speakers.yml

Mise à jour de mon nom d'utilisateur Twitter

---

_data/editions.yml

Little typo: it's "Flickr", not "Flicker"

---

_talks/2019/chaperons_and_curfews.md
_talks/2019/cherie_j_ai_retreci_mes_bundles_js.md
_talks/2019/http3.md
_talks/2019/image_at_scale.md
_talks/2019/interpreter_rum.md
_talks/2019/keeping_wikipedia_fast.md
_talks/2019/navigateur_coulisses.md
_talks/2019/pagesjaunes_top10.md
_talks/2019/performance_et_ecologie.md
_talks/2019/pwa_webperf.md
_talks/2019/responsible_javascript.md
_talks/2019/rex_protonmail.md
_talks/2019/rex_seloger.md
_talks/2019/ux_vs_dx.md
_talks/2019/why_webperf_matters.md

Ajout des vidéos

---

_talks/2019/webperf_project_checklist.md

N/A
- Prépare l'ajout de la vidéo de Quentien et Mathilde pour merge dès qu'ils sont signé le droit à l'image

Vidéo Quentin et Mathilde

---

pages/en/2020/billeterie.html

Fixes
le lien vers la billeterie depuis la page anglaise est maintenant OK

Mise à jour de la billetterie anglaise

---

pages/fr/2020/billeterie.html

Fixes #70 
on fait disparaître toute mention d'une collation
on précise ce que couvre les billets et pourquoi il peut être gratuit

correction page billeterie

---

_data/speakers.yml
_talks/2020/cdn_performance_cover_the_fonts.md

This PR is related to m4dz' talk about fonts hosting:
- en_US: improve the talk description 
- fr_FR: add translations for both talk and speaker description

Update m4dz data and translations

---

_data/schedule.yml
_includes/schedule.html
pages/fr/2020/interventions.html
pages/fr/2020/programme.html

Add tentative schedule for 2021 edition

---

_data/speakers.yml
_talks/2020/cdn_performance_cover_the_fonts.md
_talks/2020/humains_mesurer_performance.md

rajoute les traductions fournies par Gilles Dubuc (Bio, talk)

Traductions talks et bio

---

_data/sponsors.yml
_sass/base/_grid.scss

add-cdiscount-silver-sponsor

---

_config_prod.yml
_talks/2020/cdn_performance_cover_the_fonts.md
_talks/2020/cls.md
_talks/2020/concrete_utopia.md
_talks/2020/designer_cas_oublies.md
_talks/2020/humains_mesurer_performance.md
_talks/2020/moving_pictures.md

- fermeture de la vente
- ajout des liens vers les vidéos existantes (il manque des vidéos, non ?)

Fermer la vente de tickets et ajouter les liens des vidéos.

---

_config_prod.yml
_redirects
_tasks/postbuild.rake
pages/en/2021/index.html
pages/fr/2021/index.html

Il n'y a pas de lien sur le site permettant d'accéder au CFP.
Ajoute un CTA pour accéder au CFP

Adding a CTA for the CFP

---

_data/speakers.yml
_talks/2021/micro_frontend.md

Fix wording
- grosses enseignes -> grandes enseignes (moins péjoratif)

Fix wording

---

_data/sponsors.yml

Adding Scaleflex as sponsor, waiting for the verbatim.

WIP Scaleflex sponsorship

---

_data/sitemap.yml
pages/en/2021/informations.md
pages/fr/2021/infos-pratiques.md

création de la page infos pratiques 2021
Fixes #
- nouvelle page infos pratiques
- lien dans le header et le footer

création de la page infos pratiques 2021

---

pages/en/2021/interventions.html

Update year in the description of 2021 talks

---

_data/sponsors.yml

La description de Theodo date d'année précédentes de la conférence et n'est donc plus à jour
Fixes #
- Changement de la description du sponsor Theodo

Mise à jour de la description de theodo

---

README.md

Hello :)
Correction de quelques URLs erronées dans le README.md (liens morts, liens redirigés, liens vers un repo github différent..)
- MAJ du README.md

Fix urls in README

---

_includes/schedule-talk.html
_sass/ui-componants/_schedule.scss
_talks/2023/atelier-1-1.md
_talks/2023/atelier-1-2.md
_talks/2023/atelier-2-1.md
_talks/2023/atelier-2-2.md
_talks/2023/atelier-3-1.md
_talks/2023/atelier-3-2.md
_talks/2023/atelier-4-1.md
_talks/2023/atelier-4-2.md

Pas de CTA d'inscription pour les talks
- La gestion des CTA par talk était déjà gérée, j'ai juste repris le "name" du CTA sur le programme
- @jpvincent TODO ajouter les bons liens d'inscription pour chaque atelier

Gestion de CTA par talk

---

_talks/2023/atelier-1-1.md
_talks/2023/atelier-1-2.md
_talks/2023/atelier-2-1.md
_talks/2023/atelier-2-2.md
_talks/2023/atelier-3-1.md
_talks/2023/atelier-3-2.md
_talks/2023/atelier-4-1.md
_talks/2023/atelier-4-2.md

"S'inscrire" => "S'inscrire à l'atelier"

Changement de wordings

---

_config_prod.yml
_redirects
pages/en/2023/index.html
pages/en/2024/index.html
pages/fr/2023/index.html

@jpvincent Voici la PR qui ouvre le CFP.
Je te laisserai merger quand ce sera prêt de ton côté.

Ouverture du Call For Paper 2024

---

_tasks/postbuild.rake

Fix de @jpvincent afin que Netlify ne soit pas triste au deploy.

Fait marcher les liens CFP

---

pages/en/2021/index.html
pages/en/2023/index.html
pages/en/2024/index.html
pages/fr/2020/index.html
pages/fr/2021/index.html
pages/fr/2024/index.html

Fixes #
Links on English sections points to wrong places.

Fix last yeat link bugs

---

_data/speakers.yml

Fix wrong name for Umar Hansa

---

_data/schedule.yml
_talks/fr/2024/webperf-quizz.md

Talks fin de journée

---

_data/sponsors.yml

Ajour Fastly en Silver

---

_talks/en/2024/webperf-quizz.md
_talks/fr/2024/webperf-quizz.md

Nouveau speaker : nicolas Hodin

---

_talks/en/2024/how-browsers-really-load-web-pages.md
_talks/en/2024/how-i-made-the-web-more-responsive.md
_talks/en/2024/performance-debugging-with-devtools.md
_talks/en/2024/performance-is-good-for-brains.md
_talks/en/2024/pushing-webperf-limits.md
_talks/en/2024/we-love-loaf-inp.md
_talks/en/2024/webperformance-testing.md
_talks/fr/2024/HTMX-atout-SSR.md
_talks/fr/2024/alors-la-vitesse-ca-paye.md
_talks/fr/2024/evaluation-impact-environnemental-sites-web.md
_talks/fr/2024/performance-debugging-with-devtools.md
_talks/fr/2024/performance-monitoring.md
_talks/fr/2024/pushing-webperf-limits.md
_talks/fr/2024/que-fait-la-police.md
_talks/fr/2024/react-next-vs-inp-le-clash.md
_talks/fr/2024/webperf-quizz.md

Liens youtube
